### PR TITLE
Fix two bugs (whitespace and multi-line desc) in keymaps

### PR DESCRIPTION
**Pull request by wookayin**
> fix(keymaps): Fix keymaps error when desc is a multi-line string

The textual description of a keymap can have more than one lines,
in which case the previewer was emitting errors. An easy fix here would
be to join all the lines (so that 1 keymap entry == 1 line in fzf).

BEFORE:

image

AFTER:

image

> fix(keymaps): Fix whitespace handling in keymap_apply action
Need to exclude trailing whitespaces to get the lhs keycode.

For example, an entry

    "n │ c                                        │ (desc)"

should be resolved to `c`, not `c                                    `.

### CODE REVIEW

**Comment by wookayin** [comment]
BTW, although off-topic here, regarding the keymap_apply action, I'm not sure if executing an `imap` wouldn't make much sense. Also vmaps, xmaps, etc. Junegunn's original fzf.vim `Maps` command also shows normal-mode mappings (`n`).

**Comment by ibhagwan** [comment]
Ty for these @wookayin, looks great, I’ll merge this after you remove the leftover debug line.

> BTW, although off-topic here, regarding the keymap_apply action, I'm not sure if executing an `imap` wouldn't make much sense.

Not sure I understand, right now the “apply” action just feeds the key sequence, what do you mean regarding the `imap`?

> Also vmaps, xmaps, etc. Junegunn's original fzf.vim Maps command also shows normal-mode mappings (n).

Aren’t you seeing normal mode mappings in the interface?

**Comment by wookayin** [comment]
Oh wait, actualy this is wrong, rhs can contain whitespaces. Let me fix this soon
```
local key = selected[1]:match("[│]%s+([^%s]*)%s+[│]")
```

**Comment by ibhagwan** [comment]
> Oh wait, actualy this is wrong, rhs can contain whitespaces. Let me fix this soon
> 
> ```
> local key = selected[1]:match("[│]%s+([^%s]*)%s+[│]")
> ```
> 
> e.g. `<cmd>lua require'fzf-lua'<CR>`

Need to also consider `<plug>` mappings.

**Comment by wookayin** [comment]
My bad, it was about lhs. In vim keymaps lhs can't contain any whitespaces right?

**Comment by ibhagwan** [comment]
> My bad, it was about lhs. I fixed that now. In vim keymaps lhs can't contain any whitespaces right?

Not as an actual space `%s+`, it would have to be defined as `<space>`.

**Pull request merged**
