### PR TITLE
fix: offset_encoding is required now in `make_position_params` and `make_range_params`

### PR DESCRIPTION
**Pull request by rockyzhang24**
Adapt to the upstream change https://github.com/neovim/neovim/commit/629483e24eed3f2c07e55e0540c553361e0345a2 to get rid of the warning message "warning: offset_encoding is required, using the offset_encoding from the first client".

### CODE REVIEW

**Comment by ibhagwan** [comment]
Ty @rockyzhang24!

Is this backward compatible (at least down to the minimum version supported by lsp-config)?

**Comment by rockyzhang24** [comment]
Oh sorry, let me deal with it later.

**Comment by rockyzhang24** [comment]
Hi @ibhagwan, I make it backward compatible. 

After the commit https://github.com/neovim/neovim/commit/2dcbfe78fcec5f73ce061bb24b718187b9c6b134, `params` in `buf_request` can accept a function that takes the client as a parameter. So instead of sending the same params to all servers, the params with correct offset_encoding will send to each single server.

Thank you.

**Comment by ibhagwan** [comment]
Fantastic work @rockyzhang24.

I will do some testing tomorrow and merge.

**Comment by rockyzhang24** [comment]
Thank you so much for your encouragement.

**Comment by ibhagwan** [comment]
@rockyzhang24, I see you just force pushed, let me know when you feel this is ready to be merged?

**Comment by rockyzhang24** [comment]
I tried to make the code neat and clean so I wrapped the logic in a function. Just now I realized I made a big mistake and then I reverted it. Sorry for the confusion.

I think It's ready now. Thank you.

**Comment by ibhagwan** [comment]
Tyvm @rockyzhang24 for your contribution, made a few tiny improvements in https://github.com/ibhagwan/fzf-lua/commit/ce978474e406f4faacd2e66ec35d93b9e8ae069e which will make it easier to remove the backward compat in the future by deleting the `if not utils.__HAS_NVIM_011` lines.

**Comment by rockyzhang24** [comment]
@ibhagwan Really neat refinement. I learned from you how to make code clearer and more maintainable. Thank you very much for your quick response and patience.

**Comment by ibhagwan** [comment]
> @ibhagwan Really neat refinement. I learned from you how to make code clearer and more maintainable. Thank you very much for your quick response and patience.

Ty for the kind words @rockyzhang24, we all learn from each other :)

**Pull request merged**
