### PR TITLE
Experimental autogenerate docs with panvimdoc

### PR DESCRIPTION
**Pull request by mcchrish**
Experimentally autogenerate docs using https://github.com/kdheepak/panvimdoc. It gets ~90% there while 10% are some weird cases it does not generate the right look.

Feel free to close if it's not exactly what you want 😅

### CODE REVIEW

**Comment by mcchrish** [comment]
@kdheepak there are some bugs that you might want to take a look? 😁

**Comment by kdheepak** [comment]
Thanks for making the PR and bringing this to my attention! I’ll take a look at this.

**Comment by ibhagwan** [comment]
Ty, I'm not a big fan of automated documentation but it's interesting nonetheless.

Would you be able to squash this into a single commit so it's easier to review?

**Comment by kdheepak** [comment]
@mcchrish thanks for pinging me here! I made some changes that should make fix some of the formatting issues here.

**Comment by mcchrish** [comment]
Overall looks better now, but there are still some extra empty spaces in some area.

**Comment by kdheepak** [comment]
@mcchrish can you regenerate the docs again? I made some more changes and I think it should fix most if not all the spacing issues.

**Comment by ibhagwan** [comment]
I finally got to this part of my TODO list, I must say this is actually really nice and does a surprisingly good job converting the README, fantastic plugin @kdheepak!

Ty for bringing this to my attention @mcchrish, I had no idea this was even a thing and although I’d still have to write the dreaded wiki this can at least save me from the vimdoc chore.

One question though, how is the`tags` file generated, should it happen automatically once nvim detects a doc folder? It doesn’t seem to be generated for fzf-lua but other plugins do seem to have them auto generated by nvim, am I missing something?

I also tried to generate the tags file manually by running `ctags fzf-lua.txt` inside the doc folder but the tags file is generated with the top comments part only and no help tags.

**Comment by kdheepak** [comment]
I thought tags were generated by the plugin manager but I could be wrong about that. I was also meaning to look this up to figure out how to manually generate them.

**Comment by kdheepak** [comment]
Using `:helptags ALL` should re-generate all helptags for all doc directories in `runtimepath`.

**Comment by ibhagwan** [comment]
Don't ask me why, I can't even answer this myself, I decided to play around with babelfish.nvim and ended up with a [major rewrite of the converter code](https://github.com/ibhagwan/babelfish.nvim), I could have probably saved myself hours and hours of agony by just using panvimdoc but I wanted to experiment with treesitter lol

Although the code is a bit messy (TBH, at it's current state, babelfish to start with isn't very well written...) I'm quite [happy with the result](https://github.com/ibhagwan/fzf-lua/blob/main/doc/fzf-lua.txt) - let me know what you think and if there's room for improvement?

**Comment by kdheepak** [comment]
The output looks really good! I like how it handles the table with inline code in there too. I might borrow some stuff into panvimdoc too. Thanks for sharing the link to your source! I’ll go through it later. 

You should definitely consider upstreaming your version. I’m sure @mjlbach would be interested in that too. 

Should we close this PR then?

**Comment by ibhagwan** [comment]
> The output looks really good! I like how it handles the table with inline code in there too. I might borrow some stuff into panvimdoc too. Thanks for sharing the link to your source! I’ll go through it later.
> 
> You should definitely consider upstreaming your version. I’m sure @mjlbach would be interested in that too.

I just opened [babelfish.nvim#7](https://github.com/mjlbach/babelfish.nvim/pull/7) for discussion, I look at this more of a WIP since I did this "quick and dirty" and I'm not happy with the interfaces/naming/code routes.

> Should we close this PR then?

I guess we can close it, doesn't prevent is from continuing the discussion in a closed PR or maybe we can wait for the OP to close it?

**Pull request closed without merging**
