### PR TITLE
Update README to reference new default git actions

### PR DESCRIPTION
**Pull request by jpe90**
Sorry, I should have included this in the last PR.

### CODE REVIEW

**Comment by ibhagwan** [comment]
Good call, I missed this one too :-)

"it should all be in the wiki" probably, this dreaded wiki is going to take more time than coding the project lol

**Comment by jpe90** [comment]
you should just let github copilot write the wiki and accept whatever it gives you

**Comment by ibhagwan** [comment]
I doubt an automated tool would provide something I would be happy with, worth a try though.

**Comment by jpe90** [comment]
Haha sorry that was a joke :^)

**Comment by ibhagwan** [comment]
Woosh

**Pull request merged**
