### PR TITLE
feat(lsp): add incoming call handler

### PR DESCRIPTION
**Pull request by arsham**
This PR implements the `incoming_call` handler for the `lsp` provider..

### CODE REVIEW

**Comment by ibhagwan** [comment]
Ty!

https://github.com/ibhagwan/fzf-lua/commit/5060b677e02ba7ce408e7827c8187140e3dd910d - merged manually as I also added a ref for the new functoin in `init.lua:lsp_incoming_calls` (so it can be found in the `builtin` provider:

https://github.com/ibhagwan/fzf-lua/blob/5060b677e02ba7ce408e7827c8187140e3dd910d/lua/fzf-lua/init.lua#L142

Out of curiouslty what langauge servers support this functionality?

**Comment by arsham** [comment]
Thank you! Sorry I missed that part.

Out of curiosity, how did you change the commit while keeping the author of the commit?

**Comment by ibhagwan** [comment]
>Out of curiosity, how did you change the commit while keeping the author of the commit?

Great question :-)

```sh
# create a local branch of the PR
git fetch origin pull/387/head:pr_387
# switch to our local branch
git switch pr_387
# make addittional changes
git commit
# squash to one commit (not a must)
git rebase -i <commit before PR>
git switch main
git merge pr_387
git push
```

**Comment by nyngwang** [comment]
Learn git from awesome maintainers, not from those dumb books :)

**Pull request closed without merging**
