### PR TITLE
📝 added ´search´ into grep options documentation

### PR DESCRIPTION
**Pull request by Dynge**
### Problem:
Wanting to use Fzf-Lua for another project i needed to search with grep for a predefined string.
However I could find no documentation for how to search directly without needing a prompt.

### Solution:
Added `search` parameter into default configuration table in the documentation.
This allows people like me to discover how to perform instant searches for known patterns. :)

### Notes:
Thanks for this wonderful plugin <3

### CODE REVIEW

**Comment by ibhagwan** [comment]
Tysm @Dynge.

The second commit isn’t required, there is an automatic workflow to generate vimdoc from the README.

There is already an overload of options and text in the main README, it’s impossible to cover everything, don’t you think this is better suited in the Wiki (which anyone can edit)?

https://github.com/ibhagwan/fzf-lua/wiki

I started a page in the Wiki in an attempt to cover all obscure options (there are way too many, usually found in issues):

https://github.com/ibhagwan/fzf-lua/wiki/Options

**Comment by Dynge** [comment]
> The second commit isn’t required, there is an automatic workflow to generate vimdoc from the README.

Shortly after posting the pull request i noticed the latest commit message on the doc directory ^^

I can add it into the wiki. 
Are there any guidelines or review process to follow when editing the wiki or is the intended use similar to wikipedia where the community simply edits and over time it hopefully is accurate? :)

**Comment by ibhagwan** [comment]
So far there have been very few edits to the Wiki which I reviewed, I wrote most of it, no guidelines yet, hopefully this becomes big enough that guidelines are needed :)

**Comment by Dynge** [comment]
Alright. Ill try and write a few lines and examples.

Thanks for taking your time. You can close those PR if you want. 😁

**Comment by ibhagwan** [comment]
Ty @Dynge, looking forward to your edits  (no pressure at all :smile:), feel free to add this to whatever pages you see fit.

The `search` arg is briefly mentioned here:
https://github.com/ibhagwan/fzf-lua/wiki#fzf-vim-rg

**Comment by Dynge** [comment]
Added some documentation for options.

Not sure about it though. Feels much like a repeat of fzf-lua.txt 🤨

**Comment by ibhagwan** [comment]
> Added some documentation for options.
> 
> Not sure about it though. Feels much like a repeat of fzf-lua.txt 🤨

Ty @Dynge, I’m not sure myself about the best way to cover all the options, there are quite a lot undocumented spread across issues.

**Pull request closed without merging**
