### PR TITLE
feat: add lsp finder

### PR DESCRIPTION
**Pull request by sandangel**
I added the function for #669  . It's working as expected, but the UI was lagging a bit. so I think the async version is better.

Also I think I can combine `set_lsp_finder_fzf_fn` with `set_lsp_fzf_fn`, checking when method is a table or a string.

I guess we can also improve check_capabilities. When `lsp_handler.method` is a table, but 1 item is not supported by lsp, we can remove that item from `method`. 

Is this a good start? Will you open to accept this PR if I make the above improvement?

### CODE REVIEW

**Comment by sandangel** [comment]
also what are you using for code formatting? I'm using vim.lsp.buf.format get a different format.

**Comment by ibhagwan** [comment]
Ty @sandangel for the PR.

> Is this a good start? Will you open to accept this PR if I make the above improvement?

It’s a good start but if I were to merge this I would have to do this differently which is I haven’t done it yet, this is just one use case out of many and each of these requires new code which duplicates inner code, in addition it just combines the results without differentiating the source of entry (whether it cam from references, definitions, etc).

I would prefer a more generic approach where I you can combine as many providers as you wish and optionally add a prefix so you can distinguish the source of the entry, this obviously would take much more effort and I still haven’t decided on doing it.

> I guess we can also improve check_capabilities. When lsp_handler.method is a table, but 1 item is not supported by lsp, we can remove that item from method.

The reason the code is still there was backward comparability before lspconfig dropped support for older versions of neoivm, I agree it can safely be removed which I will do at one point.

**Comment by ibhagwan** [comment]
> also what are you using for code formatting? I'm using vim.lsp.buf.format with lua_ls but get a different format.

Regarding this, I use the `lua_ls` formatter but it had lots of changes recently as well as some bugs (https://github.com/CppCXY/EmmyLuaCodeStyle/issues/89) and I haven't updated `.editorconfig` yet so the formatting result is different.

**Comment by sandangel** [comment]
how about we introduce this new lsp_finder first for combining lsp related information only. At the point when we decide to work on a more generic version then we can refactor it? So it will be a small improvement over time instead of a big effort that we hesitate to do.
 
I think I add differentiating the source of entry. And all the improvements for the current code I mentioned earlier. Then we can merge. What do you think?

**Comment by sandangel** [comment]
I can add the async version and help maintain this code. does it sound good?

**Comment by ibhagwan** [comment]
> I can add the async version and help maintain this code. I will also improve it over time. does it sound good?

I thought about it and I’d rather not, the LSP code is due for a refactor and removal of deprecated settings (as you pointed out), I prefer doing it all at once together with adding a generic approach for combining providers (of all kinds, not just LSP)  rather than have to this addition into account as well.

I can’t promise when I’ll do it but it’s on the table.

**Comment by sandangel** [comment]
Thank you for saying that. Looking forward to it 😀

**Comment by sandangel** [comment]
Awesomeeeeee. Thanks alot.

**Comment by sandangel** [comment]
I will close this PR then. and again, thank you very much for supporting this. i think many users can consider this as a killer feature for them to switch fzf-lua, which already a lot faster than telescope.

**Comment by ibhagwan** [comment]
Completed in https://github.com/ibhagwan/fzf-lua/commit/a81d18ee591635ce537bfa045ed1edf7dbe30cf3

**Pull request closed without merging**
