### PR TITLE
feat(win): Automatically resize windows if screen change is detected

### PR DESCRIPTION
**Pull request by Akianonymus**
add a buffer local autocmd which will trigger the redraw() function

### CODE REVIEW

**Comment by ibhagwan** [comment]
Ty for the PR @Akianonymus!

Good idea, I'm usually careful in adding autocmd's but I guess there's no harm in automating this within fzf-lua.

**Comment by Akianonymus** [comment]
Also, consider using a formatter and adding the formatter config file to repo

It's not fun formatting by hand ( in case of big changes ).

I recommend stylua.

**Comment by ibhagwan** [comment]
> Also, consider using a formatter and adding the formatter config file to repo
> 
> It's not fun formatting by hand ( in case of big changes ).
> 
> I recommend stylua.

Stylua is too harsh for my fluent style :-)

I considered the sumneko lua formatter but I'm still debating my own view on automatic formatting.

**Comment by Akianonymus** [comment]
> > Also, consider using a formatter and adding the formatter config file to repo
> > It's not fun formatting by hand ( in case of big changes ).
> > I recommend stylua.
> 
> Stylua is too harsh for my fluent style :-)
> 
> I considered the sumneko lua formatter but I'm still debating my own view on automatic formatting.

Well, i personally don't care as long as the formatter takes care of my formatting, be it sumneko or stylua. Consistent code formatting is the priority.

**Comment by ibhagwan** [comment]
> Well, i personally don't care as long as the formatter takes care of my formatting, be it sumneko or stylua. Consistent code formatting is the priority.

I agree, I just need to allocate time to setup the `.editorconfig` to my liking:
https://github.com/sumneko/lua-language-server/wiki/Formatter

**Pull request merged**
