### PR TITLE
Set default prompt for ui_select to match the official doc

### PR DESCRIPTION
**Pull request by leiserfg**

### CODE REVIEW

**Comment by leiserfg** [comment]
The doc says:

> prompt (string|nil) Text of the prompt.
>                                     Defaults to `Select one of:`

**Comment by ibhagwan** [comment]
Ty @leiserfg, looks great!

Do you know where I can test this? I tried with spell fix (`z=`) but it seems to not yet work with `vim.ui.select` - couldn’t find anything else other than code actions that uses the new menu.

**Comment by leiserfg** [comment]
I saw that https://github.com/mickael-menu/zk-nvim is using it.

**Comment by leiserfg** [comment]
https://github.com/Shatur/neovim-session-manager is also using it, maybe having a look at https://github.com/stevearc/dressing.nvim is worth it.

**Comment by ibhagwan** [comment]
Merged, yysm @leiserfg for your conribution :-)

**Pull request merged**
