### PR TITLE
fix: escape "%" in gsub target

### PR DESCRIPTION
**Pull request by phanen**
Fix https://github.com/ibhagwan/fzf-lua/issues/1443.

### CODE REVIEW

**Comment by ibhagwan** [comment]
If doing this change we need to make sure we’re covering all lua escape chars, we can use `utils.lua_regex_escape`:
https://github.com/ibhagwan/fzf-lua/blob/985e1002b5dc70f8196ea0605bbfffc8c8407e31/lua/fzf-lua/utils.lua#L231-L240

**Comment by ibhagwan** [comment]
Just realized this happens due to the replacement string escaping and not the input string, the `%`  is probably all that’s needed.

**Comment by ibhagwan** [comment]
I knew I encountered this before :)
https://github.com/ibhagwan/fzf-lua/blob/985e1002b5dc70f8196ea0605bbfffc8c8407e31/lua/fzf-lua/core.lua#L1254-L1255

Ty @phanen!

**Comment by ibhagwan** [comment]
Looking at the code I just posted shouldn’t the replacement string gsub be 4x`%`?

**Comment by ibhagwan** [comment]
Fixed it with a force push https://github.com/ibhagwan/fzf-lua/commit/f513524561060f2b9e3bd6d36ff046bfa03ca114.

**Comment by nenahp** [comment]
Should be `4%`, I got into the second trap.

**Pull request merged**
