### PR TITLE
docs: add language annotations

### PR DESCRIPTION
**Pull request by comfortablynick**
Update docs to be able to use treesitter syntax highlighting

### CODE REVIEW

**Comment by ibhagwan** [comment]
Ty for this PR, it makes sense, the issue is this document is auto generated by [ts-vimdoc.nvim](https://github.com/ibhagwan/ts-vimdoc.nvim) so a one time fix wouldn’t be useful as it will get overwritten the next time README is updated.

This would have to be done in 2 different PRs, adding this functionality to `ts-vimdoc` and then updating the README accordingly.

**Comment by comfortablynick** [comment]
Didn't know that. This won't be very useful, then!

I assume there's some way for your tool to take the language of the code from Markdown and translate it to vimdoc.

**Comment by ibhagwan** [comment]
> Didn't know that. This won't be very useful, then!
> 
> I assume there's some way for your tool to take the language of the code from Markdown and translate it to vimdoc.

Of course there is (via tree-sitter which is already used to parse the markdown), it’s just has to be coded into the tool now :)

**Comment by ibhagwan** [comment]
FYI, 

Added this functionality was added to `ts-vimdoc.nvim` in: https://github.com/ibhagwan/ts-vimdoc.nvim/commit/eb25fc912ff73cae9a003158a7413448ccdb20e5

Also added it as a CI workflow (https://github.com/ibhagwan/fzf-lua/commit/72cf10ea41819a95e29c114c744b6376642ce3e0) and applied to the main branch (https://github.com/ibhagwan/fzf-lua/commit/725276b860b041d5d93232d5ea212c901b4a00ff).

**Pull request closed without merging**
