### PR TITLE
Improved the execution speed of external commands.

### PR DESCRIPTION
**Pull request by uga-rosa**
#126
I also fixed some problems that I noticed. For example, `vim.fn.systemlist()` returns an empty string when it fails, so there is no point in displaying it as an error message. So, I made it so that it displays the command that was executed.

### CODE REVIEW

**Comment by ibhagwan** [comment]
This is not yet ready to be merged, first the `get_stdout` function dose not recognize shell errors properly, I added `lua_io` as a parameter for testing and it returns different results than `systemlist`:

```lua
:lua _G.dump(require'fzf-lua.stdio'.get_stdout("echo 1", false))   -- { "1" } false  <-- OK
:lua _G.dump(require'fzf-lua.stdio'.get_stdout("echo 1", true))    -- { "1" } false  <-- OK
:lua _G.dump(require'fzf-lua.stdio'.get_stdout("badcmd", false))   -- "" true        <-- OK
:lua _G.dump(require'fzf-lua.stdio'.get_stdout("badcmd", true))    -- {} false       <-- NOT OK
```

Second, this messes up the error message coming out of `is_git_repo()`, due to the function unable to detect the shell error code it always returns `false` and the users won't see the error message `fatal: not a git repository (or any parent up to mount point /)`.

Also, this might need a rebase soon, I've decided to drop the two git commands to detect changes and just run `git status -s` instead.

**Comment by uga-rosa** [comment]
Oh, I was mistaken. It's true that we can't recognize stderr this way.
I can use `vim.loop` to get stderr, but it is asynchronous, so I need to be creative.

I understand about the `git status -s`. I'll wait.

**Comment by ibhagwan** [comment]
Just committed the change, test it out, even with `systemlist` it should be faster since I removed the untracked command and now using only `git status -s` to get all git indicators.

**Comment by uga-rosa** [comment]
Unfortunately, the speed was not fast enough for regular use, although it was better :_(
I'll try to find out more about the cause.

**Comment by ibhagwan** [comment]
> Unfortunately, the speed was not fast enough for regular use, although it was better :_(
> I'll try to find out more about the cause.

I'll also work on your `io.popen` idea, if I can make it exactly equal to `systemlist` then why not.

**Comment by uga-rosa** [comment]
If use is limited, 2>&1 may be a good solution.

I'll close this PR and fork it again.
I'm a beginner, so I don't know much about git operations yet. Haha.

**Comment by ibhagwan** [comment]
Just FYI, if you want to update your PR next time:

```sh
git reset --mixed HEAD^2    # undo your two commits (doesn't change files on disk)
git reset --hard HEAD       # resets the working dir to the current HEAD
                            # (will have discarded your on disk changes)

git remote add upstream https://github.com/ibhagwan/fzf-lua.git
git fetch upstream
git rebase upstream/main
...
<work on your new changes>
...
git push --force            # overwrite the PR branch effectively updating this PR
```

**Comment by uga-rosa** [comment]
Thx!

**Pull request closed without merging**
