### PR TITLE
Display Selected Highlight Group In Colorscheme Provider

### PR DESCRIPTION
**Pull request by barrett-ruth**
Currently, running `:FzfLua highlights` doesn't actually do *anything* when an entry is selected.

I think it is logical to display the highlighted group in the command line as if `:hi <group>` was run.

### CODE REVIEW

**Comment by ibhagwan** [comment]
Ty @barrett-ruth!

**Comment by barrett-ruth** [comment]
@ibhagwan can you uhhh... look at my review please! I should've marked the PR as draft - there's *definitely* two duplicate lines of code when it comes to displaying the hl group.

**Comment by ibhagwan** [comment]
> @ibhagwan can you uhhh... look at my review please! I should've marked the PR as draft - there's _definitely_ two duplicate lines of code when it comes to displaying the hl group.

Whoops, I looked at the code figured what it was supposed to do and tested it quickly and saw it working

**And** missed the duplicate lines lol

Let me know if you’d like to fix it with another PR or I ca remove one of these.

**Comment by ibhagwan** [comment]
I’m confused, removing any line prevents the hl from being displayed in `:messages`… this only works when both lines exist, I must leave soon so I’ll have to take care of this later, if you have any insight feel free to submit a fix PR.

**Comment by barrett-ruth** [comment]
OK. I found that was the case too - not sure why lol. I was also just wondering if there was any more elegant way to write the code, but I found it all to be functional myself. Thanks for the quick review.

**Pull request merged**
