### PR TITLE
feat(windows): support windows path and pipe

### PR DESCRIPTION
**Pull request by linrongbin16**
1. use loopback IPv4 address `127.0.0.1:0` for `serverstart` API (in `init.lua`).
2. support windows temporary pipe path for preview socket (in `shell_helper.lua`).
3. support windows HOME directory (`$env:USERPROFILE`) (in `path.lua`).

Note: this PR still not really working on Windows. I'm still testing the `files` API (with `fzf` `rg` `bat`).

TODO: regression test on macOS, to make sure not break on macOS.

### CODE REVIEW

**Comment by ibhagwan** [comment]
Ty @linrongbin16!

Can you squash the commits into a single concise commit? Would it make it easier to track this way.

**Comment by linrongbin16** [comment]
sure, before squash commits, I still have many issues, it may be a little bit long, hope you have time to read.

## Issue-1
After start nvim, I execute `require('fzf-lua').files()`, then got this error:
image

I'm trying to search the code, find where does this command come from, finally I add log [shell.log - line-98](https://github.com/ibhagwan/fzf-lua/pull/772/files#diff-d0b3a8917528052acdac3b46bd7cac54889ed96ba442ef0e905a65744bb80789R98), it gives me this log:
```
2023-06-05 21:41:32: [shell|M.raw_async_action] id(number):1, action_cmd(string):'"C:\\Program Files\\Neovim\\bin\\nvim.exe" -n --headless --clean --cmd "lua loadfile([[C:/Users/rlin/github/linrongbin16/fzf-lua/lua/fzf-lua/shell_helper.lua]])().rpc_nvim_exec_lua({fzf_lua_server=[[127.0.0.1:50198]], fnc_id=1 })" -- {}'
```
It looks like the same.

## Issue-2
So I copied the `action_cmd` and execute it from windows powershell, it gives me another error:
image
The log in [shell_helper.lua - line-74](https://github.com/ibhagwan/fzf-lua/pull/772/files#diff-8532b280cbb0a12c5576d30b2b9b1c21b80b93d281ed90053736c7097053e2e6R74) is:
```
2023-06-05 21:48:33: [shell_helper|rpc_nvim_exec_lua] chan_id(number):3, opts(table):{
2023-06-05 21:48:33:   fnc_id = 1,
2023-06-05 21:48:33:   fzf_lua_server = "127.0.0.1:50198"
2023-06-05 21:48:33: }
```
I have no idea, why `chan_id` not working?

**Comment by linrongbin16** [comment]
In [fzf.lua - line-200](https://github.com/ibhagwan/fzf-lua/pull/772/files#diff-11eb9949b4b2b3cbdc4270bc2eb03c813b4cfbd137b7b9460c2a1632d2a70631R200), I found it's executing the fzf command:
```
2023-06-05 22:05:17: [fzf|M.raw_fzf] opts.is_fzf_tmux(nil):nil, jobstart(function):<function 1>, cmd(string):'C:/Users/rlin/AppData/Local/nvim/lazy/fzf/bin/fzf  --info=default --multi --expect=ctrl-c,ctrl-q,esc --print-query --bind="ctrl-l:toggle-preview,ctrl-u:half-page-up,ctrl-d:half-page-down" --prompt="~\\github\\linrongbin16\\fzf-lua/" --preview-window=nohidden:border:nowrap:right:90% --layout=reverse --preview="""C:\\Program Files\\Neovim\\bin\\nvim.exe"" -n --headless --clean --cmd ""lua loadfile([[C:/Users/rlin/github/linrongbin16/fzf-lua/lua/fzf-lua/shell_helper.lua]])().rpc_nvim_exec_lua({fzf_lua_server=[[127.0.0.1:50312]], fnc_id=1 })"" -- {}" --height=100% --ansi --border=none > "C:\\Users\\rlin\\AppData\\Local\\Temp\\nvim.0\\erIVt6\\1"'
```

It looks very close to the result command of `requre('fzf-lua').files()`, I opened a windows powershell and execute this command directly:
image

It shows another error (the `sh` cannot correct parse the windows path `""C:\\Program Files\\Neovim\\bin\\nvim.exe""` with whitespace):
image

**Comment by ibhagwan** [comment]
> It shows another error (the sh cannot correct parse the windows path ""C:\\Program Files\\Neovim\\bin\\nvim.exe"" with whitespace):

Perhaps space needs to be shell escaped?

**Comment by linrongbin16** [comment]
Update (it's not relate to this PR, but the motivation is):

## Short version
I found a way to support rg's `--iglob` option (technically any rg options) with [fzf.vim](https://github.com/junegunn/fzf.vim) plugin.

See source code in my neovim config:
1. [FzfLiveGrep](https://github.com/linrongbin16/lin.nvim/blob/3d4306d8594e21438a2b2f0fe171d290ea4fdad6/repo/junegunn/fzf.vim/config.vim#L20): customize fzf `change:reload` option, pass user input to a custom query command(a wrapper on rg).
2. [~/.nvim/bin/lin_fzf_live_grep.py](https://github.com/linrongbin16/lin.nvim/blob/3d4306d8594e21438a2b2f0fe171d290ea4fdad6/bin/lin_fzf_live_grep.py#L1): the custom query command, it will pass user input, put parameters after `--` as rg's `--iglob` option.

## Long version

The motivation of this PR, is that [fzf.vim](https://github.com/junegunn/fzf.vim) not support live grep by file type. For example, I want to search `fzf` in all *.lua files, in fzf-lua, I just use:
```lua
            require("fzf-lua").live_grep({
                cmd = "rg --column -n --no-heading --color=always -S",
                rg_glob = true,
            })
```

Then in user input prompt, input: `fzf -- *.lua`, it will be all good. This feature is a very important key when I develop big project.

Here's some pros and cons among fzf-lua, fzf.vim and telescope.nvim:

* fzf-lua - pros: performant fzf, `--iglob` support, cons: only macOS/linux.
* fzf.vim - pros: performant fzf, support windows, cons: lack of rg `--iglob` option support.
* telescope.nvim - pros: support rg's raw options (via telescope-live-grep-args.nvim extension), support windows, cons: draggy and stuck animation under big project (even with telescope-fzf-native.nvim extension).

That's why I'm thinking bring fzf-lua to windows.

But today I suddenly found a document: [fzf.vim-with-glob](https://github.com/haphamdev/fzf.vim-with-glob), using its method, and it worked!

**Comment by ibhagwan** [comment]
> But today I suddenly found a document: [fzf.vim-with-glob](https://github.com/haphamdev/fzf.vim-with-glob), using its method, and it worked!

Very nice @linrongbin16, FYI, with a bit of effort anything with fzf-lua is probably also possible with fzf.vim and even directly at the shell, in my shell I have git and live grep variants and even have a grep version with switching between live grep and fuzzy matching, if you’re interested you can find it [in my dotfiles fzf functions](https://github.com/ibhagwan/dots/blob/de5f16873675e108ce0f401c02745b45ba4b619c/.config/zsh/fzf_git_functions.sh#L90-L102).

**Comment by linrongbin16** [comment]
> > But today I suddenly found a document: [fzf.vim-with-glob](https://github.com/haphamdev/fzf.vim-with-glob), using its method, and it worked!
> 
> Very nice @linrongbin16, FYI, with a bit of effort anything with fzf-lua is probably also possible with fzf.vim and even directly at the shell, in my shell I have git and live grep variants and even a grep version with switching between live grep and fuzzy matching, if you’re interested you can find it [in my dotfiles fzf functions](https://github.com/ibhagwan/dots/blob/de5f16873675e108ce0f401c02745b45ba4b619c/.config/zsh/fzf_git_functions.sh#L90-L102).

thanks for sharing!

**Comment by linrongbin16** [comment]
close for no further working, thanks to auther.

**Comment by ibhagwan** [comment]
@linrongbin16, did you give up to particular issue or you no longer have time to work on this?

**Comment by linrongbin16** [comment]
> @linrongbin16, did you give up to particular issue or you no longer have time to work on this?

yes

**Comment by ibhagwan** [comment]
@linrongbin16, I know you got your own plug-in now but just in case you’re interested windows is now supported follow #1038 and the [windows branch](https://github.com/ibhagwan/fzf-lua/tree/windows) for more info.

If you haven’t figured it windows nested quoted escaping with cmd.exe you might want to take a look at `libuv.shellescape` and the testing done in `tests\libuv_spec.lua`.

**Pull request closed without merging**
