### PR TITLE
Add windows support [WIP]

### PR DESCRIPTION
**Pull request by TheLeoP**
This draft PR is intended to track the progress of adding windows support [as suggested](https://github.com/ibhagwan/fzf-lua/issues/954#issuecomment-1863871390) in #954.

@GitMurf 

TODO:
- [ ] Test escaping with every command (things like nested double quotes or passing lua strings through `cmd.exe` have proven to bee really tricky). The most complicated command yet has been `FzfLua live_grep` because `cmd.exe` loves eating double quotes.
    - [x] Check why `FzfLua live_grep` doesn't work with regexes (probably an escaping problem) and fix it. What does insert the `^`?
    - [x] Make `FzfLua live_grep` work for simple searches.
- [x] ~Handle separators as per #957 because windows loves `:`~ It looks like this isn't a path problem, but a `cmd` problem (again)
- [x] Handle separators as per #957 because windows loves `:` (for real this time). Solving an issue with colons in `make_entry.file` made the pickers act weird unless I manually increase the `--with-nth` value
- [ ] Do not only check if os is windows, check if the current shell is `cmd.exe` (low priority, can be done at the end).
- [ ] Check problems related with preview using shell commands
    - [ ] alternatives to git_diff using `sh -c`
- [x] Check live grep `exec_empty_query` conditioning
    - [x] Is this the same thing that makes `FzfLua live_grep` always fail before writing anything? Probably yes
- [ ] Add support for quickstart on Windows (?)
- [x] Why do commands like `FzfLua blines` or `FzfLua autocmds` show repeated entries?
- [ ] Use `vim.fs.normalize` on windows where appropiate
- [ ] Why do `ctrl-n` and `ctrl-p` do not work in buffers?

### CODE REVIEW

**Comment by ibhagwan** [comment]
This is a great start @TheLeoP!

If you haven’t yet, I think it’s also worthwhile checking out fzf’s wiki regarding known limitations on windows and making sure we mention these in fzf-lua if/where applicable:
https://github.com/junegunn/fzf/wiki/Windows

**Comment by TheLeoP** [comment]
@ibhagwan I hadn't found that info yet, thanks. Would this have to be added to the README, the neovim documentation, the wiki or all three?

**Comment by ibhagwan** [comment]
> @ibhagwan I hadn't found that info yet, thanks. Would this have to be added to the README, the neovim documentation, the wiki or all three?

I think it’s worth a mention on the README, I linked this so we can explore what of these limitations affects fzf-lua in functionality in case we have to disable it by code.

**Comment by TheLeoP** [comment]
I have a question regarding style. It seems like the current `stylua.toml` results in a style that gives warnings for lua-ls (since it has style cheking enabled). Is this intended?

**Comment by ibhagwan** [comment]
> I have a question regarding style. It seems like the current `stylua.toml` results in a style that gives warnings for lua-ls (since it has style cheking enabled). Is this intended?

I have stylua configured as I tested it but I eventually settled on the formatted that comes with `lua_ls` and is configured in `.editorconfig`.

**Comment by GitMurf** [comment]
@TheLeoP awesome! When you are ready for a windows user to test, let me know and I can test and try to help out in that way :)

**Comment by GitMurf** [comment]
> - [ ] Test escaping with every command (things like nested double quotes or passing lua strings through `cmd.exe` have proven to bee really tricky). The most complicated command yet has been `FzfLua live_grep` because `cmd.exe` loves eating double quotes.

Curious have you tried with PowerShell instead of cmd?

**Comment by ibhagwan** [comment]
@TheLeoP, given all the styling changes it’s a bit difficult for me to focus on the meaningful changes but from what I could gather it looks like amazing work so far! At one point when you feel the code is ready it might be worthwhile to merge it into a separate branch so we can work on it together and maybe even call for windows testers on Reddit.

**Comment by TheLeoP** [comment]
@ibhagwan Sorry, I hadn't realized how much styling noice stylua caused while I had it turn on. I tried to reduce most of it.

> At one point when you feel the code is ready it might be worthwhile to merge it into a separate branch so we can work on it together and maybe even call for windows testers on Reddit.

Sounds great, I'll let you know when I think the PR is ready.

**Comment by TheLeoP** [comment]
> Curious have you tried with PowerShell instead of cmd?

Yep. Escaping it's easier because powershell has both `'` and `"`, and sane esacaping rules. But, it's slower to start a powershell session than a `cmd` one and fzf internally uses `cmd` as shell on windows (at least by default).

@GitMurf

**Comment by ibhagwan** [comment]
> @ibhagwan Sorry, I hadn't realized how much styling noice stylua caused while I had it turn on. I tried to reduce most of it.

No worries, I’ll handle it either way, if later we feel a different and more opinionated styling makes sense (such as stylua) I’m not against it.

> > At one point when you feel the code is ready it might be worthwhile to merge it into a separate branch so we can work on it together and maybe even call for windows testers on Reddit.
> 
> Sounds great, I'll let you know when I think the PR is ready.


Ty @TheLeoP, looking forward to it!

**Comment by TheLeoP** [comment]
The string used in `--delimiter` is a regex, right? So, for example `["--delimiter"] = "'[:]'"`, is matching all characters inside the `[]`, in this case only `:`, right? Are the `'` intended to be part of the regex? Or is it because of a shell thing on posix shells?

I think that I was wrong in #957 because, apparently, removing the pair of `'` from the delimiter on Windows seems to solve the problem I was having.

**Comment by ibhagwan** [comment]
> The string used in `--delimiter` is a regex, right? So, for example `["--delimiter"] = "'[:]'"`, is matching all characters inside the `[]`, in this case only `:`, right? Are the `'` intended to be part of the regex? Or is it because of a shell thing on posix shells?

Correct it’s a regex, from [man fzf] [-d](https://www.mankier.com/1/fzf#-d)
```man
-d --delimiter=STR
Field delimiter regex for --nth and --with-nth (default: AWK-style)
```

> Are the `'` intended to be part of the regex? Or is it because of a shell thing on posix shells?

I’ve experimented with different delimiters, if it’s just one char the single ticks can probably be removed but will have to be tested again.

> I think that I may have been wrong in #957 because, apparently, removing the pair of `'` from the delimiter on Windows seems to solve the problem I was having.

If it works on other platforms too by all means remove it.

**Comment by TheLeoP** [comment]
> If it works on other platforms too by all means remove it.

Windows seems to require `"` instead of the `'`, for now I feel more confortable doing this change only on windows.

**Comment by TheLeoP** [comment]
By the way, I'm realizing that some commands, like `blines` are showing duplicate entries. Do you have an idea of whay may be causing this?

Picture as reference:

image

**Comment by ibhagwan** [comment]
> > If it works on other platforms too by all means remove it.
> 
> Windows seems to require `"` instead of the `'`, for now I feel more confortable doing this change only on windows.

Replacing `'` with `”` is a pretty safe change, in fact that’s what `libuv.shellescape` does for fish shell# (due to issues documented in the code).

**Comment by ibhagwan** [comment]
> By the way, I'm realizing that some commands, like `blines` are showing duplicate entries. Do you have an idea of whay may be causing this?
> 

Strange indeed, no idea why this happens, perhaps something due to like 230 in fzf.lua:
```lua
handle_contents = vim.schedule_wrap(function()
```

Any specific reason you decided to `vim.schedule_wrap` the function?

**Comment by TheLeoP** [comment]
> Strange indeed, no idea why this happens, perhaps something due to line 230 in fzf.lua:

I'll look into it tomorow.

> Any specific reason you decided to `vim.schedule_wrap` the function?

Since the Windows implementation uses libuv `pipe`s, the callbacks couldn't call neovim api functions and I was getting a lot of errors. But I'll also double check that tomorrow.

**Comment by TheLeoP** [comment]
I couldn't resist taking a quick look and it seems that removing the `vim.schedule_wrap` does solve the problem (but calling API functions still throws errors)

**Comment by ibhagwan** [comment]
> > Strange indeed, no idea why this happens, perhaps something due to line 230 in fzf.lua:
> 
> I'll look into it tomorow.
> 
> > Any specific reason you decided to `vim.schedule_wrap` the function?
> 
> Since the Windows implementation uses libuv `pipe`s, the callbacks couldn't call neovim api functions and I was getting a lot of errors. But I'll also double check that tomorrow.

I see, without windows this only affects some use-cases as mentioned here (regarding `vim.schedule`:
https://github.com/ibhagwan/fzf-lua/wiki/Advanced#lua-function-as-contents

**Comment by ibhagwan** [comment]
> I couldn't resist taking a quick look and it seems that removing the `vim.schedule_wrap` does solve the problem (but calling API functions still throws errors)

Lucky guess. :)

Now that makes me even more curious why… why would scheduling something outside of vim’s “fast event” cause this duplication.

Perhaps there is another way to rid of the errors without scheduling? If you point out to me which calls are throwing the errors I can think of something.

**Comment by TheLeoP** [comment]
> If you point out to me which calls are throwing the errors I can think of something.

Depends on the command used. In `FzfLua blines`, for example, its this line:

https://github.com/ibhagwan/fzf-lua/blob/407323ade0ebca1bb4f26453c1aacbb246654139/lua/fzf-lua/providers/buffers.lua#L25

**Comment by ibhagwan** [comment]
> > If you point out to me which calls are throwing the errors I can think of something.
> 
> Depends on the command used. In `FzfLua blines`, for example, its this line:
> 
> https://github.com/ibhagwan/fzf-lua/blob/407323ade0ebca1bb4f26453c1aacbb246654139/lua/fzf-lua/providers/buffers.lua#L25

Got it, so basically every `vim.` call, anywhere, one solution would be to `vim.schedule` only the affected providers contents generation but that’s just a bandaid, anyone using fzf_exec on windows will face similar issues.

**Comment by TheLeoP** [comment]
> Got it, so basically every `vim.` call, anywhere, one solution would be to `vim.schedule` only the affected providers contents generation but that’s just a bandaid, anyone using fzf_exec on windows will face similar issues.

Yeah, that's what I was thinking. Tomorrow I'll try to understand why scheduling this causes the lines to be duplicated and hopefully I'll be able to find a better solution. Thanks for your time c:

**Comment by ibhagwan** [comment]
> > Got it, so basically every `vim.` call, anywhere, one solution would be to `vim.schedule` only the affected providers contents generation but that’s just a bandaid, anyone using fzf_exec on windows will face similar issues.
> 
> Yeah, that's what I was thinking. Tomorrow I'll try to understand why scheduling this causes the lines to be duplicated and hopefully I'll be able to find a better solution. Thanks for your time c:

Is it possible like 385 in fzf.lua should be moved up inside the if clause? Not sure about the flow yet but is it possible it’s called twice like this (once from the pipe callback and a second time at said line)?

**Comment by TheLeoP** [comment]
> Is it possible line 385 in fzf.lua should be moved up inside the if clause? Not sure about the flow yet but is it possible it’s called twice like this (once from the pipe callback and a second time at said line)?

That was exactly the problem, thanks

**Comment by ibhagwan** [comment]
> > Is it possible line 385 in fzf.lua should be moved up inside the if clause? Not sure about the flow yet but is it possible it’s called twice like this (once from the pipe callback and a second time at said line)?
> 
> That was exactly the problem, thanks

Great!

**Comment by TheLeoP** [comment]
Is the `buffer` (picker? Telescope calls them pickers but I'm not sure what are they called here) supposed to do nothing for `ctrl-n` and `ctrl-p`?

**Comment by ibhagwan** [comment]
> Is the `buffer` (picker? Telescope calls them pickers but I'm not sure what are they called here) supposed to do nothing for `ctrl-n` and `ctrl-p`?

There are no default binds setup for ctrl-p/n for any provider (picker), if you setup `- -history` these will be bind to next/prev history, otherwise these will be inherited from `FZF_DEFAULT_OPTS`.

**Comment by TheLeoP** [comment]
In other pickers I'm able to go up and down the result list using `ctrl-n` and `ctrl-p`, but not in `buffers`

**Comment by ibhagwan** [comment]
> In other pickers I'm able to go up and down the result list using `ctrl-n` and `ctrl-p`, but not in `buffers`

Explore the come binds with debug=true,  I can go next/prev with ctrl-p/n in buffers.

**Comment by ibhagwan** [comment]
@TheLeoP, it's probably wise to dedup and save in a static the `is_windows` var, I've noticed a few locations where the condition is wrong (missing the `== 1` part) which obviously causes issues on non-windows platforms:
image


Perhaps a static `__IS_WINDOWS` under `utils` below these lines?
https://github.com/ibhagwan/fzf-lua/blob/407323ade0ebca1bb4f26453c1aacbb246654139/lua/fzf-lua/utils.lua#L11-L14

**Comment by ibhagwan** [comment]
Looks great @TheLeoP, the only file I wouldn’t change is `libuv.lua` since it’s loaded a stand-alone (to proxy shell cmdw) file it shouldn’t contain any requires to other files, while it does work due to the require hack I added it’s probably safer without a first line `require`.

**Comment by TheLeoP** [comment]
> Looks great @TheLeoP, the only file I wouldn’t change is `libuv.lua` since it’s loaded a stand-alone (to proxy shell cmds) file it shouldn’t contain any requires to other files, while it does work due to the require hack I added it’s probably safer without a first line `require`.

Sorry, I made the change without thinking.

**Comment by ibhagwan** [comment]
Ty @TheLeoP! Let me know when you feel it’s stable enough for me to start trading on Linux/Mac.

**Comment by ibhagwan** [comment]
@TheLeoP, I wanted to start testing this, I'm also trying to get my hands on a windows VM so I can help you with this PR, in the meantime to make this easlier I carefully rebased on main and a few tiny modifications (reduced extra styling noise).

This way I can also add commits if I see stuff that needs fixing, the next commits you add would you be able to rebase and add them on top of the `windows` branch?

https://github.com/ibhagwan/fzf-lua/tree/windows

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/d94ca001c83ea04188a74eb21f447265c78ed493 - this commit adds a wrapperfor the `vim.fs.normalize` calls reducing some lines of code.

**Comment by TheLeoP** [comment]
Just to be clear. Currently, all of the changes on this PR are already on the `windows` branch, right?. Should I close this PR and open a new one targetting the `windows` branch and continue from there?

**Comment by ibhagwan** [comment]
> Just to be clear. Currently, all of the changes on this PR are already on the `windows` branch, right?. Should I close this PR and open a new one targetting the `windows` branch and continue from there?

Correct, all changes from this PR were rebase-merged into a single commit (under your authorship).

> Should I close this PR and open a new one targetting the windows branch and continue from there?

Preferably we can rebase this PR onto the new branch but if you find opening a new PR easier I have no problem with that.

**Comment by ibhagwan** [comment]
@TheLeoP, something interesting (still WIP), I was able to retire the complex escaping logic you added for `cmd /c` quoting. unlike `sh -c`, with `cmd -c` you can keep adding arguments after the `fzf` command, for example in UNIX `sh -c 'fzf' --ansi` isn't valid, the entire command needs to be in inside the quotes.

However with `cmd` you can write the command as;
```cmd
cmd /c fzf --ansi --prompt "foo> "
```
Which means we can pass the arguments as table elements directly to `jobstart|termopen`, this is some rough WIP and lots of things still fail (previews, etc), but I got the command `:FzfLua files previewer=false` with this commit **without calling the special windows escape function**: https://github.com/ibhagwan/fzf-lua/commit/9e198d6e49932434f9721b712de482991c6eb49e

**Comment by TheLeoP** [comment]
> something interesting (still WIP), I was able to retire the complex escaping logic you added for cmd /c quoting

That's great, escaping was proving to be complex and this may be a more stable option in the long run.

Also, I'm sorry for not being able to contribute to the PR lately. Next week I'll try to put time into it. Thanks for all the help :3

**Comment by ibhagwan** [comment]
> > something interesting (still WIP), I was able to retire the complex escaping logic you added for cmd /c quoting
> 
> That's great, escaping was proving to be complex and this may be a more stable option in the long run.
> 
> Also, I'm sorry for not being able to contribute to the PR lately. Next week I'll try to put time into it. Thanks for all the help :3

Ty @TheLeoP and no worries there is no rush on this, I’m also traveling this week so I will only be able to continue next weekend.

**Comment by ibhagwan** [comment]
@TheLeoP, I think I’ve nailed it, it’s still not perfect but it seems we have to use a very specific logic for shell escaping on windows, we definitely can’t use `vim.fn.shellescape` on windows which simple doubles the double quotes.

The logic you created was in fact a patch to try and fix the bad quoting caused by using `vim.fn.shellescape`, with the new logic which I will link below all we have to do us simply make sure all the occurrences of `vim.fn.shellescape` are replaced with the adjusted (for windows) `libuv.shellescape`.

Instead of explaining again what I discovered I’ll just link the solution, it’s quite an interesting read about window' super retarded quote escaping/stripping logic:
https://stackoverflow.com/questions/6714165/powershell-stripping-double-quotes-from-command-line-arguments

And here is the implementation which I briefly tested and works with actions, even git_status stage/unstafe works:
https://github.com/ibhagwan/fzf-lua/blob/d4266bd71596a4463c47a55a3915ef958daaac1b/lua/fzf-lua/libuv.lua#L492-L546

**Comment by TheLeoP** [comment]
I tried to force-push the windows branch into this PR, but it got closed automatically (?), so I'll open a new PR. Shold I continue with the same TODO list? I haven't take a deep look into the changed of the windows branch yet

**Comment by ibhagwan** [comment]
> I tried to force-push the windows branch into this PR, but it got closed automatically (?), so I'll open a new PR. Shold I continue with the same TODO list? I haven't take a deep look into the changed of the windows branch yet

Maybe because I've been force pushing into the branch repeatedly as I'm working on it as we speak, now that I know you're on it I won't override the commits.

I will rebase-merge the branch so that it has 2 commits, one for my changes and another for yours and we can build on that, I believe that would be most straight forward.

> I haven't take a deep look into the changed of the windows branch yet

Quite a lot of changes, I rewrote the `path` module to be cross platform, while the changes are bigger I believe this will benefit us in future changes.

> Shold I continue with the same TODO list?

We should probably have a combined TODO list.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/76268b158f15957021c11d8f8750bdace0a03d53

@TheLeoP - this is the latest rebased commit in the windows branch, I won't overwrite it from now on, only add new changes.

Note the path module was rewritten and there are now tests under `test\path_spec.lua` which you can run if you have the `plenary.nvim` plugin installed with `:PlenaryBustedDirectory tests`

**Pull request closed without merging**
